apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-deployments
  namespace: default
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: stop-deployments-serviceaccount
          containers:
          - name: stop-deployments
            image: kowshickraj/stopdeploymentsjob
          restartPolicy: OnFailure
