apiVersion: v1
kind: ServiceAccount
metadata:
  name: stop-deployments-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: stop-deployments-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stop-deployments-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stop-deployments-serviceaccount
    namespace: default
roleRef:
  kind: Role
  name: stop-deployments-role
  apiGroup: rbac.authorization.k8s.io
